### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by abieler** [JuliaStats/RegERMs.jl#14]
I just tried running the example from the docs, which did not work.

```julia
using RegERMs
# define some toy data (XOR - example)
np = 100
nn = 100
X = [randn(int(np/2),1)+1 randn(int(np/2),1)+1; randn(int(np/2-0.5),1)-1 randn(int(np/2-0.5),1)-1;
     randn(int(nn/2),1)+1 randn(int(nn/2),1)-1; randn(int(nn/2-0.5),1)-1 randn(int(nn/2-0.5),1)+1] # examples with 2 features
y = vec([ones(np,1); -ones(nn,1)])       # binary class values

# choose SVM as learning algorithm
svm = SVM(X, y; kernel=:rbf)

# get solution (regularization parameter is 0.1)
regParam = 0.1
model = optimize(svm, regParam)

# make predictions and compute accuracy
ybar = predict(model, X)
acc = mean(ybar .== y)
```
Error message says predict is not defined.
Any comments?
Thanks
Andre

**Comment by BigCrunsh** [comment]
@abieler: Sorry, I forgot to update the readme (which is done now). Should be working now.

**Comment by abieler** [comment]
Hi Christoph,

the Quick Start example in the docs still does not work for me, using
Julia version 0.3.10.


Here is what I ran:

using RegERMs
# define some toy data (XOR - example)
np = 100
nn = 100
X = [randn(int(np/2),1)+1 randn(int(np/2),1)+1; randn(int(np/2-0.5),1)-1
randn(int(np/2-0.5),1)-1;
     randn(int(nn/2),1)+1 randn(int(nn/2),1)-1; randn(int(nn/2-0.5),1)-1
randn(int(nn/2-0.5),1)+1] # examples with 2 features
y = int(vec([ones(np,1); -ones(nn,1)]))       # binary class values

# use rbf kernel by using mercer map
map = MercerMap(X, :rbf)
X = RegERMs.apply(map)

# choose (linear) SVM as learning algorithm with regularization parameter
0.1
svm = SVM(X, y; λ=0.1)

# get a solution
model = optimize(svm)

# make predictions and compute accuracy
ybar = predict(model, X)
acc = mean(ybar .== y)


and got a complaint about λ.

ERROR: unrecognized keyword argument "λ"
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading
/home/abieler/scripts/julia/machineLearning/regErms_example.jl, in
expression starting on line 14


(I would include the "using RegERMs" line in the
example so people just could copy and paste the example.


Best,

Andre

**Comment by BigCrunsh** [comment]
Sorry, I have not bumped up the version number yet, so you are probably using RegERMs 0.0.1. I will do it asap. In the meanwhile you can check out the current version by
```julia
Pkg.checkout("RegERMs")
```

FYI: I added your recommended line to the readme.

**Comment by BigCrunsh** [comment]
Version number is updated. @abieler: the example should work after an update.
